INSERT INTO DB_OBJ (TYPE, OWNER, NAME)
SELECT 'PROCEDURE', 'U1', 'P1' FROM DUAL
 WHERE NOT EXISTS (SELECT NULL FROM DB_OBJ)
 UNION ALL
SELECT 'TABLE', 'U1', 'T1' FROM DUAL
 WHERE NOT EXISTS (SELECT NULL FROM DB_OBJ)
 UNION ALL
SELECT 'TABLE', 'U1', 'T2' FROM DUAL
 WHERE NOT EXISTS (SELECT NULL FROM DB_OBJ);

INSERT INTO DEPENDENCY (OBJ_ID, REF_ID)
SELECT 1, 2 FROM DUAL
 WHERE NOT EXISTS (SELECT NULL FROM DEPENDENCY)
UNION ALL
SELECT 1, 3 FROM DUAL
 WHERE NOT EXISTS (SELECT NULL FROM DEPENDENCY);

INSERT INTO IO_TAG (PROC_ID, TAB_ID, IS_IN, IS_OUT)
SELECT 1, 2, TRUE, FALSE FROM DUAL
 WHERE NOT EXISTS (SELECT NULL FROM IO_TAG)
 UNION ALL
SELECT 1, 3, FALSE, TRUE FROM DUAL
 WHERE NOT EXISTS (SELECT NULL FROM IO_TAG);