CREATE TABLE IF NOT EXISTS DB_OBJ (
    ID IDENTITY PRIMARY KEY,
    TYPE VARCHAR(23) NOT NULL,
    OWNER VARCHAR(128) NOT NULL,
    NAME VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS DEPENDENCY (
    ID IDENTITY PRIMARY KEY,
    OBJ_ID BIGINT NOT NULL,
    REF_ID BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS IO_TAG (
    ID IDENTITY PRIMARY KEY,
    PROC_ID BIGINT NOT NULL,
    TAB_ID BIGINT NOT NULL,
    IS_IN BOOLEAN,
    IS_OUT BOOLEAN
);