spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath*:db/schema-h2.sql
      data-locations: classpath*:db/data-h2.sql

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console